# Generated by Django 4.1.2 on 2022-10-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_info',
            name='live_in',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
